### ISSUE TITLE
Where can you edit blip images?

### ISSUE THREAD

**Issue by davwheat** [TGRHavoc/live_map#10]
Is there any way to edit the blip images for people in vehicles, helicopters, on ground, etc?

If not could you add this?

**Comment by TGRHavoc** [comment]
Are you talking about on the interface? If so, you could edit the [spritesheet](https://github.com/TGRHavoc/live_map-interface/blob/master/images/icons/blips_texturesheet.png) to change how they look.

Other than that, you can change the icon that is shown when in a certain vehicle (e.g. Show a helicopter icon when in a car) then you can edit the [client/client.lua](https://github.com/TGRHavoc/live_map/blob/master/client/client.lua#L63) file.

**Comment by davwheat** [comment]
The spritesheet is the one I wanted! Thanks 🥇
