### ISSUE TITLE
Remove players from dropdown/combobox after they have disconnected.

### ISSUE THREAD

**Issue by davwheat** [TGRHavoc/live_map#15]
Players usernames stay in the player list after they have disconnected.

**Comment by TGRHavoc** [comment]
This should already be fixed (see [socket.js](https://github.com/TGRHavoc/live_map-interface/blob/master/js/src/socket.js#L122) in the interface).

Do you have a repro case that I can use to get this behaviour?

**Comment by jiynn** [comment]
Does this always happen or only sometimes? Could be a browser issue that just needed a simple refresh. I've had it happen maybe twice.
