### ISSUE TITLE
Blips Disappear after server restart

### ISSUE THREAD

**Issue by jiynn** [TGRHavoc/live_map#17]
I was able to install the map with no issues, however as soon as I restart the server, the blips are no longer available on the live map. Everything else seems to work, just the blips don't save.

**Comment by TGRHavoc** [comment]
Are you using the `blips generate` command in-game. If yes, do you see any messages in console after you've ran it?

**Comment by jiynn** [comment]
looks like a permissions error based on the console, where is the blips file supposed to save? in the /var/www or the /server-data/livemap?

**Comment by TGRHavoc** [comment]
`server-data/resources/livemap/<blip_file>`

So, if you've not changed the "blip_file" convar, it would be
`server-data/resources/livemap/server/blips.json`

**Comment by jiynn** [comment]
"LiveMap couldn't save the blips to file.. Maybe the directory isn't writable?"

are you familiar with linux?

**Comment by TGRHavoc** [comment]
> are you familiar with linux?
Yes, I've also ran into this on my own server running Ubuntu. Chmod-ing the directory didn't seem to work so, I had to change the "blip_file" convar to just "blips.json".

Could you try that?

**Comment by jiynn** [comment]
That worked.

I also had tried chmod & chown with zero luck.

Thanks for the help.
