### ISSUE TITLE
Map freezes randomly stops showing live locations?

### ISSUE THREAD

**Issue by jiynn** [TGRHavoc/live_map#18]
Not sure if it's due to another user logging on and watching, or what it is, but the other night while playing, we wanted to keep all players closely together, so we used the map to watch locations, and it seemed as if only 1 person could watch the map live at a time. No errors were thrown, but I did have to do a "/restart live_map" command in game to get it to work again before a few seconds later it would freeze up again.

**Comment by TGRHavoc** [comment]
Could you set the `debug_level` to 2 and observer the output before it crashes?

**Comment by jiynn** [comment]
Sure, I'll set it and test it tonight.

**Comment by TGRHavoc** [comment]
Ok.. I think I found the problem and fixed it, could you test out 2.2.3 for me and see if it works?

**Comment by jiynn** [comment]
Absolutely, I'll test it tonight when everyone gets online.

**Comment by KjayCopper** [comment]
Your lucky you can get it to connect, mines won't connect to the server

**Comment by jiynn** [comment]
KjayCopper... if you need help, I'd be more than happy to help get you setup... just a heads up, I'm setting this up in linux. Add my steam (same as this username)
