### ISSUE TITLE
Player Location disappears when not moving

### ISSUE THREAD

**Issue by jiynn** [TGRHavoc/live_map#21]
Not only does the blip disappear, but due to lack of movement, the map says that user isn't online until they move again.

I was afking while checking code, then noticed, so not sure on how long it takes, but it doesn't seem long.

**Comment by TGRHavoc** [comment]
The players not appearing until they move is a unintended side effect of the new system... I might have a way to solve this, it's a bit late at the moment.

As for the players disappearing, that should happen as the "playerLeft" data doesn't get sent until the player leaves (should be the only way the player marker gets removed).

**Comment by jiynn** [comment]
I'm going to try to replicate it again... Last circumstances:

Police Car, engine off (vehcontrol mod), not moving.

**Comment by jiynn** [comment]
Seems to be on load of website for viewing... If player is not moving AT ALL... in a car or not... the map won't pick up on it at all. The second they do, it picks it up.

**Comment by TGRHavoc** [comment]
Yea, I'll see if I can fix that tomorrow (shouldn't be too hard)

**Comment by jiynn** [comment]
Sounds good. Keep up the good work, this is amazing!

Add me on steam.

**Comment by jiynn** [comment]
Also having an issue with reporting correct location... it seems to be lagging behind really badly
