### ISSUE TITLE
Map interface loading issue

### ISSUE THREAD

**Issue by jiynn** [TGRHavoc/live_map#22]
Just re-downloaded the live map and live map interface, and am now seeing this issue when moving around on the interface. I can confirm this on 2 computers.

![image](https://user-images.githubusercontent.com/33206565/32385973-2428e394-c096-11e7-9b2b-68a045c38d05.png)

**Comment by TGRHavoc** [comment]
Please make sure you have all the [map images downloaded](https://github.com/TGRHavoc/live_map-interface/releases/tag/v0.1) and located in the appropriate folder.
