### ISSUE TITLE
LiveMap couldn't save the blips to file.. Maybe the directory isn't writable?

### ISSUE THREAD

**Issue by XxROBOTICSxX** [TGRHavoc/live_map#26]
Upon running the /blips generate command as an admin, the following error is provided via console, "LiveMap couldn't save the blips to file.. Maybe the directory isn't writable?"
I have ensured that all directories, sub directories and files are owned by the user running the server and are readable, writable, and executable by that user.

**Comment by TGRHavoc** [comment]
Could you look at [this issue/solution](https://github.com/TGRHavoc/live_map/issues/17#issuecomment-341185431) and see if it fixes your problem?

**Comment by XxROBOTICSxX** [comment]
That fixes the issue. Thanks.
