### ISSUE TITLE
Google API

### ISSUE THREAD

**Issue by AdamorfuX** [TGRHavoc/live_map#31]
I get an error on the live map saying "This page can not load Google Map correctly." 
Here are some screenshots of the issue.
![image](https://user-images.githubusercontent.com/31371003/45577817-4ce0ef80-b87e-11e8-9371-e10d3f6c920b.png)
![image](https://user-images.githubusercontent.com/31371003/45577830-65e9a080-b87e-11e8-8083-2c58b21fb79a.png)

**Comment by TGRHavoc** [comment]
This is a known issue. You can either ignore the message and not be able to use the different map images (i.e. satalite). Or, use the code from @davwheat 's PR: https://github.com/TGRHavoc/live_map-interface/pull/18

Note: using the PR will require you to get a valid key from Google. You may even be able to get $200 free credit. See https://github.com/TGRHavoc/live_map-interface/issues/17 for more info.

**Comment by AdamorfuX** [comment]
Ok, thanks!
