### ISSUE TITLE
 Error getting blips! blip cache is empty

### ISSUE THREAD

**Issue by Tom-NL** [TGRHavoc/live_map#34]
Error getting blips! blip cache is empty how fix the error?

**Comment by lyrics1988123** [comment]
me2, did you found a solution?

**Comment by TGRHavoc** [comment]
@Tom-NL sorry for the late reply.
Please refer to the [FaQ](https://docs.tgrhavoc.me/livemap-resource/faq/#how-do-i-get-blips) section of the documentation website.
