### ISSUE TITLE
Fails to work with Linux

### ISSUE THREAD

**Issue by chrisrogersukgb** [TGRHavoc/live_map#36]
Hello, im trying to upgrade this on my Linux Server but now its stating that it can not find or install the "webpack" resource? do you have any guides or tutorials on how to install WebPack on linux builds? as what ive read it states Webpack is unsupported?

**Comment by TGRHavoc** [comment]
Someone on the forum has had the same issues. The only potential solution I've seen is to install the dependencies manually and modify the __resource.lua file.

1. Make sure NodeJS and NPM are installed for your distro 
2. Navigate to the resource's location 
3. Run `npm install`
4. Remove `dependency "yarn"` from the resource file
5. Try starting again

If this doesn't fix the issue then, I believe the only thing you can do is build the server yourself with support... Not exactly sure how you would do that but, apparently others have been.
