### ISSUE TITLE
Couldnt Start Resource LIvemap

### ISSUE THREAD

**Issue by Hamz20** [TGRHavoc/live_map#37]
I downloaded the resource, I didn't make any changes to it, I added it into the Resource Folder and Started it.
For some reason in the console, it says it couldn't start the resource.
If anyone knows why, please let me know!

**Comment by JustinRijsdijk** [comment]
@Hamz20 Is your FXServer updated to the latest Server build?

**Comment by Hamz20** [comment]
Yes it is!

**Comment by JustinRijsdijk** [comment]
Can you list for me: your server os and your fx-server build number

**Comment by Hamz20** [comment]
Linux and 1976 Build Number

**Comment by Hamz20** [comment]
It worked on our Dev Server a month ago, when we tried it on the Main Server the resource doesn't start for some reason...

**Comment by JustinRijsdijk** [comment]
> Linux and 1976 Build Number
What Linux distribution? and is your dev server on the same OS as your main server?

**Comment by Hamz20** [comment]
Im not sure what Linux Distribution, as our other dev had set it up but yes the dev server is the same OS as the main server.

**Comment by Hamz20** [comment]
Maybe there is a resource interfering with the livemap? or could it be a fault in the config?

**Comment by JustinRijsdijk** [comment]
Would you be able to join this discord server (this is for the live_map addons) https://discord.gg/NbRYZT
Then we can discuss it over there

**Comment by Hamz20** [comment]
I joined

**Comment by KjayCopper** [comment]
@Hamz20 is there any error log or does it just say can't start
