### ISSUE TITLE
Error to getting the blips

### ISSUE THREAD

**Issue by wil2005-development** [TGRHavoc/live_map#40]
Hello,
If we do the command blips generate, it will not load the blips on the server and on the website, how can we fix this?

**Comment by TGRHavoc** [comment]
What errors do you get in console? I've tried to make them as helpful as possible...

**Comment by Tom-NL** [comment]
Hey,
we have checked everything and tried kwa settings and I know that there is no ssl on the subdomain because I have not put it on it yet, but it does not work, do you know a solution for this?


![image](https://user-images.githubusercontent.com/46630574/76781592-42731f00-67af-11ea-811f-01110bd03090.png)
and 
![image](https://user-images.githubusercontent.com/46630574/76781628-5159d180-67af-11ea-87c0-e01cfdf483a0.png)

**Comment by wil2005-development** [comment]
![Screenshot 2020-03-16 at 18 10 19](https://user-images.githubusercontent.com/56365974/76783037-73ecea00-67b1-11ea-8507-d1743b25fcf2.png)

**Comment by wil2005-development** [comment]
2020-03-16 18:08:55+01:00: [WARN] LiveMap Sockets - Someone tried connecting from an invalid origin: http://livemap.dutchgamingscommunity.nl
2020-03-16 18:09:05+01:00: [WARN] LiveMap Sockets - Someone tried connecting from an invalid origin: http://livemap.dutchgamingscommunity.nl
Sending heartbeat to https://servers-ingress-live.fivem.net/ingress
2020-03-16 18:09:53+01:00: [WARN] LiveMap Sockets - Someone tried connecting from an invalid origin: http://livemap.dutchgamingscommunity.nl

**Comment by TGRHavoc** [comment]
And have you got access control convar set to `http://livemap.dutchgamingscommunity.nl`?

**Comment by wil2005-development** [comment]
yes, in the server.cfg

**Comment by wil2005-development** [comment]
set socket_port 30121
set livemap_debug "warn" # "[all]" 'trace', 'debug', 'info', 'warn', 'error', 'fatal', 'off'
set blip_file "server/blips.json"
set livemap_access_control "https://www.livemap.dutchgamingscommunity.nl/"

**Comment by TGRHavoc** [comment]
Secure connections will only work with a reverse proxy set up at the minute. So, if you want that you'll have to look up how to do it on your webserver.

Anyways, remove the leading slash from the end, the https and the www.
