### ISSUE TITLE
Error parsing script @live_map/dist/livemap.js in resource live_map: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by DoJoMan18** [TGRHavoc/live_map#42]
Hello,

I'm getting an error when I start the livemap. 

```
Error parsing script @live_map/dist/livemap.js in resource live_map: SyntaxError: Invalid or unexpected token
Failed to load script dist/livemap.js.
```

**Comment by TGRHavoc** [comment]
You tried packing the script manually?

**Comment by DoJoMan18** [comment]
So I just did a reverse of a backup that I had laying around. Livemap is running without a error but it seems like the websocket port is closed for some reason. I do not have a firewall running at this time, and this happend after we moved from our server host. Do I have to install something extra on a ubuntu server?

**Comment by TGRHavoc** [comment]
Could bump the debugging to `info` and see if the resource starts listening on the port you think it is.

**Comment by DoJoMan18** [comment]
I fixed it while updating yarn and webpack.
