### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by TGRHavoc** [TGRHavoc/live_map#43]
Original issue posted: https://forum.cfx.re/t/release-livemap/49901/986?u=havoc

Info:
GameServer: Zap-hosting (Windows)

What I've tried:
Added `start yarn` and `start webpack` to my server.cfg.
Tried both commenting out and leaving the yarn and webpack dependencies in the __resource.lua.

Here is the printout of the logs surrounding webpack and yarn:

```
> Found new resource webpack in C:/cygwin\home\zap529355\g247734\gta5-fivem\server-data/resources//[system]/[builders]/webpack
Found new resource yarn in C:/cygwin\home\zap529355\g247734\gta5-fivem\server-data/resources//[system]/[builders]/yarn
...
Creating script environments for yarn
Started resource yarn
Creating script environments for webpack
Started resource webpack
...
Running build tasks on resource live_map - it'll restart once completed.
**Couldn't start resource live_map.**
...
yarn install v1.21.0
info No lockfile found.
[1/4] Resolving packages...
warning webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
...
[3/4] Linking dependencies...
error Could not write file "C:\\cygwin\\home\\zap529355\\g247734\\gta5-fivem\\server-data\\resources\\live_map\\yarn-error.log": "EPERM: operation not permitted, open 'C:\\cygwin\\home\\zap529355\\g247734\\gta5-fivem\\server-data\\resources\\live_map\\yarn-error.log'"
error An unexpected error occurred: "EPERM: operation not permitted, mkdir 'C:\\cygwin\\home\\zap529355\\g247734\\gta5-fivem\\server-data\\resources\\live_map\\node_modules'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by TGRHavoc** [comment]
Looks like the dependencies for LiveMap have been deprecated.

**Comment by Atlas7005** [comment]
Been months now, could you fix this please?

**Comment by TGRHavoc** [comment]
I wish I could. I've got to wait for these builders to finish putting insulation in our new house before we can move in... Unfortunately any development from me is entirely dependant on how quickly they can finish (they should have finished two bloody months ago).

**Comment by TGRHavoc** [comment]
Yup. They are slow arse builders... Just waiting for a new gas connection now...  Knowing them, that'll take another 7 months 😢

**Comment by UPandaOfficial** [comment]
Hey Havoc! Just wondering if there is an update on the current status as I am getting the EXACT same error, and have scene other servers running it so wondering if there is another method to get around this. Thanks!

**Comment by TGRHavoc** [comment]
Just realised... If you're getting the _exact_ same error, it could be a permission issue on Linux. Make sure fivem has permission to write to the live_map folder... Should be enough to keep the resource running until I update dependencies.

Cc. @Atlas7005 @Vestedmarius @UPandaOfficial
