### ISSUE TITLE
Access denied for command blips.

### ISSUE THREAD

**Issue by wil2005-development** [TGRHavoc/live_map#48]
Hello dear,

We want to generate the blips file. We have give us in the server.cfg the group admin. Do you have a fix for it. We have no errors from the console or f8. 

Kind regards,

William

**Comment by TGRHavoc** [comment]
No fix. Just make sure you've got the permissions right. If it's not, the resource won't work...
Also, this hasn't been updated to the latest version of FiveM yet so, I dont know if it would be that... I do have some updated code but, haven't found the time to test and push them yet...

In other words, make sure your permissions are actually correct. I will try and reproduce but, you've not given me much info to work with.
