### ISSUE TITLE
Error with starting the resource

### ISSUE THREAD

**Issue by Malaros** [TGRHavoc/live_map#49]
I have an error with starting the resource on my server [Screen 1](https://prnt.sc/wbjfnx) [Screen 2](https://prnt.sc/wbjge6)

**Comment by TGRHavoc** [comment]
Looks like a permission issue. Make sure that FiveM has permission to write to the resource directory.

**Comment by Malaros** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/65315474/103220415-7e333b80-4920-11eb-856f-1b8be0181235.png)
New error

**Comment by Malaros** [comment]
Do you have discord, can u watch over?

**Comment by TGRHavoc** [comment]
@Malaros same error. Permission issue. Not an issue with livemap.

**Comment by Malaros** [comment]
Fixed it, how can i change the language of this map?
