### ISSUE TITLE
License Plate doesn't get removed from data

### ISSUE THREAD

**Issue by matsn0w** [TGRHavoc/live_map#68]
**Describe the bug**
When entering a vehicle, the license plate gets added to the player data. ([here](https://github.com/TGRHavoc/live_map/blob/2fde18da59b1b47a0d92c0cffa8c7cbcf78d39b8/example_client/client_vehicle_info.lua#L41)). This works fine, except that it won't get removed after leaving the vehicle.

**To Reproduce**
1. Enter a vehicle
2. Watch player data in the interface
3. Leave vehicle
4. Watch player data again, license plate should still be visible

**Expected behavior**
License plate should be removed from player info.

**Screenshots**
![image](https://user-images.githubusercontent.com/15019582/130782095-a316acae-9f05-4081-b28f-09d236b641d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser: Microsoft Edge
 - Version: 92.0.902.78

**Possible Solution**
Not sure what's going on, I tried adding some different kind of info (emergency status, see example below) and this works as expected.

**Additional context/Screenshots**
In `doVehicleUpdate()`:
```lua
-- check if the siren is turned on
local siren_on = IsVehicleSirenOn(vehicle)

-- add the emergency status to the data table
data["Emergency"] = siren_on and "Yes" or "No"

-- update the player data
TriggerServerEvent("livemap:UpdatePlayerData", "Emergency", data["Emergency"])
```

and 

```lua
Citizen.CreateThread(function()
    while true do
        Wait(10)

        if NetworkIsPlayerActive(PlayerId()) then

            -- Update Vehicle (and icon)
            if IsPedInAnyVehicle(PlayerPedId()) then
                doVehicleUpdate()

            elseif data["Licence Plate"] ~= nil or data["Vehicle"] ~= nil then
                -- No longer in a vehicle, remove "Licence Plate" if present
                data["Licence Plate"] = nil
                data["Vehicle"] = nil
                data["Emergency"] = nil
                temp["vehicle"] = nil

                -- Remove it from socket communication
                TriggerServerEvent("livemap:RemovePlayerData", "Licence Plate")
                TriggerServerEvent("livemap:RemovePlayerData", "Emergency")
                TriggerServerEvent("livemap:RemovePlayerData", "Vehicle")
            end
        end
    end
end)

**Comment by TGRHavoc** [comment]
> 
> 
> **Describe the bug**
> When entering a vehicle, the license plate gets added to the player data. ([here](https://github.com/TGRHavoc/live_map/blob/2fde18da59b1b47a0d92c0cffa8c7cbcf78d39b8/example_client/client_vehicle_info.lua#L41)). This works fine, except that it won't get removed after leaving the vehicle.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Enter a vehicle
> 
>     2. Watch player data in the interface
> 
>     3. Leave vehicle
> 
>     4. Watch player data again, license plate should still be visible
> 
> 
> **Expected behavior**
> License plate should be removed from player info.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/15019582/130782095-a316acae-9f05-4081-b28f-09d236b641d1.png)
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 10 Pro 64-bit
> 
>     * Browser: Microsoft Edge
> 
>     * Version: 92.0.902.78
> 
> 
> **Possible Solution**
> Not sure what's going on, I tried adding some different kind of info (emergency status, see example below) and this works as expected.
> 
> **Additional context/Screenshots**
> In `doVehicleUpdate()`:
> 
> ```lua
> -- check if the siren is turned on
> local siren_on = IsVehicleSirenOn(vehicle)
> 
> -- add the emergency status to the data table
> data["Emergency"] = siren_on and "Yes" or "No"
> 
> -- update the player data
> TriggerServerEvent("livemap:UpdatePlayerData", "Emergency", data["Emergency"])
> ```
> 
> and
> 
> ```lua
> Citizen.CreateThread(function()
>     while true do
>         Wait(10)
> 
>         if NetworkIsPlayerActive(PlayerId()) then
> 
>             -- Update Vehicle (and icon)
>             if IsPedInAnyVehicle(PlayerPedId()) then
>                 doVehicleUpdate()
> 
>             elseif data["Licence Plate"] ~= nil or data["Vehicle"] ~= nil then
>                 -- No longer in a vehicle, remove "Licence Plate" if present
>                 data["Licence Plate"] = nil
>                 data["Vehicle"] = nil
>                 data["Emergency"] = nil
>                 temp["vehicle"] = nil
> 
>                 -- Remove it from socket communication
>                 TriggerServerEvent("livemap:RemovePlayerData", "Licence Plate")
>                 TriggerServerEvent("livemap:RemovePlayerData", "Emergency")
>                 TriggerServerEvent("livemap:RemovePlayerData", "Vehicle")
>             end
>         end
>     end
> end)
> ```

Yup. Because I can't keep my spelling of "Licence Plate" consistent... 

@all-contributors add @matsn0w for bug

**Comment by TGRHavoc** [comment]
@all-contributors please add @matsn0w for bug

**Comment by matsn0w** [comment]
Lol, thanks bro :)

**Comment by matsn0w** [comment]
Oh, now you've fixed it the wrong way around XD I'll submit a PR.

**Comment by matsn0w** [comment]
see #70
