### ISSUE TITLE
Live map not found as a resource.

### ISSUE THREAD

**Issue by Ryanhindman6654** [TGRHavoc/live_map#77]
I installed the resource as the install instruction state but the resource is failing to be found on the server. Is there a way to fix this issue so I can be found?

Thank you

**Comment by TGRHavoc** [comment]
I've never come across this issue before.... Are you sure you're putting the files you see in this repo into a folder inside your resources folder?

It would look something like this:
```
F:\FX-SERVER\RESOURCES
├───live_map
    ├───.github
    │   └───ISSUE_TEMPLATE
    ├───.vscode
    ├───client
    ├───dist
    ├───docs
    ├───example_client
```

**Comment by Ryanhindman6654** [comment]
Yes. I checked the file format. The issue appeared to be with the reverse proxy, and it fixed itself a few days later.
