### ISSUE TITLE
Issue with the websockets

### ISSUE THREAD

**Issue by TheGamingGinger** [TGRHavoc/live_map#90]
Hi there,

I´ve setup everything according to the documentation and it seems liek the interface can´t connect with the websocket
of the FiveM resource.

I´m always getting this error:
![image](https://user-images.githubusercontent.com/88145223/187177265-0dee4c49-e582-4fcf-b51e-b1d217e98c8c.png)

I wrote everything in the server.cfg file
![image](https://user-images.githubusercontent.com/88145223/187177571-7899364d-dd53-46e4-a9c0-3c8ab9c3856f.png)

Downloaded the latest version
![image](https://user-images.githubusercontent.com/88145223/187177807-a9f66c61-e0e4-44c2-a1f2-9b6b22ed4f1f.png)

And setup the interface
![image](https://user-images.githubusercontent.com/88145223/187178138-5d3e0b4f-3f4f-4500-beb2-8603dc609975.png)

Aswell as the document root in the apache httpd.conf
![image](https://user-images.githubusercontent.com/88145223/187179228-1bf55d1e-7ad6-4f5a-bd6f-4fd78d89d56f.png)

I haven´t been able to get some help in any FiveM Discord Server I´m in so I´m trying the more "direct" way.
Would really appreciate the help. 

Thanks in advance.

**Comment by TGRHavoc** [comment]
Going to close this as I think v4 will fix all these issues. With moving to SSE you will be able to use the Nucleus proxy to have a secure connection instead of creating a reverse proxy yourself (much simple, very wow).
